export const REQUEST_CREATE_COUPON = "REQUEST_CREATE_COUPON";
export const SUCCESS_CREATE_COUPON = "SUCCESS_CREATE_COUPON";
export const FAIL_CREATE_COUPON = "FAIL_CREATE_COUPON";

export const REQUEST_GET_ALL_COUPONS = "REQUEST_GET_ALL_COUPONS";
export const SUCCESS_GET_ALL_COUPONS = "SUCCESS_GET_ALL_COUPONS";
export const FAIL_GET_ALL_COUPONS = "FAIL_GET_ALL_COUPONS";

export const REQUEST_DELETE_COUPON = "REQUEST_DELETE_COUPON";
export const SUCCESS_DELETE_COUPON = "SUCCESS_DELETE_COUPON";
export const FAIL_DELETE_COUPON = "FAIL_DELETE_COUPON";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const NEW_COUPON_RESET = "NEW_COUPON_RESET";