export const CREATE_PRESCRIPTION_REQUEST = 'CREATE_PRESCRIPTION_REQUEST';
export const CREATE_PRESCRIPTION_SUCCESS = 'CREATE_PRESCRIPTION_SUCCESS';
export const CREATE_PRESCRIPTION_FAIL = 'CREATE_PRESCRIPTION_FAIL';

export const GET_ADMIN_PRESCRIPTIONS_REQUEST = 'GET_ADMIN_PRESCRIPTIONS_REQUEST';
export const GET_ADMIN_PRESCRIPTIONS_SUCCESS = 'GET_ADMIN_PRESCRIPTIONS_SUCCESS';
export const GET_ADMIN_PRESCRIPTIONS_FAIL = 'GET_ADMIN_PRESCRIPTIONS_FAIL';

export const DELETE_PRESCRIPTION_REQUEST = 'DELETE_PRESCRIPTION_REQUEST';
export const DELETE_PRESCRIPTION_SUCCESS = 'DELETE_PRESCRIPTION_SUCCESS';
export const DELETE_PRESCRIPTION_FAIL = 'DELETE_PRESCRIPTION_FAIL';

export const GET_ALL_PRESCRIPTIONS_REQUEST = 'GET_ALL_PRESCRIPTIONS_REQUEST';
export const GET_ALL_PRESCRIPTIONS_SUCCESS = 'GET_ALL_PRESCRIPTIONS_SUCCESS';
export const GET_ALL_PRESCRIPTIONS_FAIL = 'GET_ALL_PRESCRIPTIONS_FAIL';
